name: Hindu_jhatka
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  badges: ^3.1.2
  get: ^4.6.6
  provider: ^6.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Carousel images/
    - assets/Our_best_sellings/
    - assets/Chicken/
    - assets/Mutton/
    - assets/SeaFood/
    - assets/Pork/
    - assets/Eggs/
